[General]
Background="Backgrounds/mecha.jpg"
ScreenWidth=1920
ScreenHeight=1080
BlurRadius=20
FormPosition="left"
HaveFormBackground=true
PartialBlur=true
MainColor="white"
AccentColor="#d3d3d3"
BackgroundColor="#2d2d2d"
RoundCorners=20
Font="JetBrainsMono Nerd Font"
FontSize=14
